[tool.briefcase]
project_name = "rokucontroller"
bundle = "com.neoscreenager"
version = "0.0.1"
url = "https://neoscreenager.com/rokucontroller"
license = "MIT license"
author = 'Abhishek Mathur'
author_email = "neoscreenager@gmail.com"

[tool.briefcase.app.rokucontroller]
formal_name = "rokucontroller"
description = "Roku TV Controller Using Roku Remote API"
icon = "src/rokucontroller/resources/rokucontroller"
sources = ['src/rokucontroller']
requires = []


[tool.briefcase.app.rokucontroller.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev20',
]

[tool.briefcase.app.rokucontroller.linux]
requires = [
    'toga-gtk>=0.3.0.dev20',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.rokucontroller.windows]
requires = [
    'toga-winforms>=0.3.0.dev20',
]

# Mobile deployments
[tool.briefcase.app.rokucontroller.iOS]
requires = [
    'toga-iOS>=0.3.0.dev20',
]

[tool.briefcase.app.rokucontroller.android]
requires = [
    'toga-android>=0.3.0.dev20',
]
